// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

// Load .env.local when DB URLs aren't set (Next.js often uses .env.local)
if (!process.env["DATABASE_URL"] || !process.env["DIRECT_URL"]) {
  config({ path: resolve(process.cwd(), ".env.local") });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate, studio, introspect) needs a direct/session connection.
    // App runtime uses DATABASE_URL (pooled) via src/lib/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
